name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  build:
    # Change @main to @v0.3.1 here
    uses: haobogu/rmk/.github/workflows/user_build.yml@v0.3.1
    with:
      keyboard_toml_path: "keyboard.toml"
      vial_json_path: "vial.json"
