jobs:
  build:
    # Change from @v0.3.1 to @rmk-v0.8.2
    uses: haobogu/rmk/.github/workflows/user_build.yml@rmk-v0.8.2
    with:
      keyboard_toml_path: "keyboard.toml"
      vial_json_path: "vial.json"
